### ISSUE TITLE
Port Twitter clone to Hexagon v3

### ISSUE THREAD

**Issue by jaguililla** [hexagonkt/twitter_clone#3]
Update dependency to Hexagon v3.0.x. Tests should complete properly.

Some modules (like 'dependency injection') may have been moved to the `hexagon_extra` repository.

In the process of porting the example, maybe the documentation is not complete enough and you have to rely on the code. Don't miss this opportunity to improve the documentation 😉 .

**Comment by alky003** [comment]
Hi @jaguililla this is my first time contributing could you please explain me exactly what I have to do.

**Comment by jaguililla** [comment]
Hello @alky003 and thanks for your help and support!

The purpose of this task is to port the [Twitter Clone](https://github.com/hexagonkt/twitter_clone) example from Hexagon v1 (the previous toolkit version) to the latest one: v2.0.25.

There are big changes among these two versions.

Steps to tackle this task are:
1. Clone the Twitter Clone repository
2. Build the example in it's current state
3. Upgrade dependencies in Gradle script (including the Hexagon version)
4. Fix compile errors.
5. Make repository tests pass

I will assign the task to you, if you prefer to work on something else just let me know :)

Thanks again... And happy coding!!!

**Comment by jaguililla** [comment]
Hello, is there any progress on this task?

**Comment by jaguililla** [comment]
The code has been ported (no compile errors), but the tests don't pass.
